import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { InitialScreen } from './components/InitialScreen'
import { InitialHeader } from './components/InitialHeader'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>スタート画面</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <InitialHeader />
      </header>
      <main className={styles.main}>
        <InitialScreen />
      </main>
    </>
  )
}
